### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by kamillag** [Tyrath/T113-VLN#7]
QSqlDatabase db = QSqlDatabase.addDatabase("QMYSQL");
        db.setHostName("bigblue");
        db.setDatabaseName("flightdb");
        db.setUserName("acarlson");
        db.setPassword("1uTbSbAs");
        boolean ok = db.open();

**Comment by BeanBean-Nyah** [comment]
http://doc.qt.io/qt-4.8/sql-driver.html


https://katecpp.wordpress.com/2015/08/28/sqlite-with-qt/
